---

- name: TOWER | pre-tasks
  hosts: tower_db_primary
  become: true
  gather_facts: false
  tasks:

  - name: TOWER | pre-tasks | Generate Public Key
    user:
      name: ansible
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
    tags:
     - always

  - name: TOWER | pre-tasks | Grab the contents of the tower db server public key
    fetch:
      src: /home/ansible/.ssh/id_rsa.pub
      dest: /tmp/towerdbkey.pub
      flat: yes
    changed_when: false
    tags:
     - always

- name: TOWER | pre-tasks
  hosts: tower_nodes,tower_db*
  become: true
  gather_facts: false
  tasks:

  - name: TOWER | pre-tasks | Setup passwordless SSH for Ansible Tower Installation
    authorized_key:
      user: ansible
      state: present
      key: "{{ lookup('file', '/tmp/towerdbkey.pub') }}"
    tags:
     - always

  - name: TOWER | pre-tasks | Setup passwordless sudo for ansible user
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%ansible\s'
      line: '%ansible ALL=(ALL) NOPASSWD: ALL'
  
  - name: TOWER | pre-tasks | set umask
    command: sed -i 's/umask 027/umask 022/g' /etc/profile /etc/bashrc
    tags:
      - always

- name: TOWER | filesystems
  hosts: tower_db_primary,tower_db_secondary
  become: true
  roles:
    - tower-db-filesystems

- name: TOWER | installation
  hosts: tower_db_primary
  become_user: ansible
  become: true
  environment:
    ANSIBLE_HOST_KEY_CHECKING: False
  roles:
    - tower-cluster-install

- name: TOWER | configuration
  hosts: tower_nodes
  become: true
  roles:
   - tower-cluster-config

- name: TOWER | setup PostgreSQL replication
  hosts: tower_db_primary
  become_user: ansible
  become: true
  environment:
    ANSIBLE_HOST_KEY_CHECKING: False
  roles:
    - tower-db-replication
